version: "3.9"

services:
  slackbot:
    build:
      context: .
      dockerfile: dev.dockerfile
    container_name: nemo_bot_dev
    ports:
      - ${DB_PORT}:5001

    environment:
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
      SLACK_NOTIFICATION_CHANNEL: ${SLACK_NOTIFICATION_CHANNEL}
      PORT: ${DB_PORT}
      GOOGLE_CALENDAR_API_KEY: ${GOOGLE_CALENDAR_API_KEY}
      GOOGLE_CALENDAR_ID: ${GOOGLE_CALENDAR_ID}
      SANITY_PROJECT_ID: ${SANITY_PROJECT_ID}
      SANITY_DATA_SET: ${SANITY_DATA_SET}
      AXIOM_API_TOKEN: ${AXIOM_API_TOKEN}
      DB_URL: ${DB_URL}

  mongo:
    build: ./utils/config/mongodb_rs
    container_name: mongo_database
    restart: always
    environment:
      MONGO_INITDB_DATABASE: nemo
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27018
      MONGO_COMMAND: "mongosh"

    ports:
      - "27018:27018"

    healthcheck:
      # Use "mongo" instead of "mongosh" before v5.0
      test:
        [
          "CMD",
          "mongosh",
          "admin",
          "--port",
          "27017",
          "--eval",
          "db.adminCommand('ping').ok",
        ]
      interval: 5s
      timeout: 2s
      retries: 20
