version: "3.9"

services:
  slackbot:
    build: .
    container_name: nemo_bot
    ports:
      - ${DB_PORT}:5001

    environment:
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
      SLACK_NOTIFICATION_CHANNEL: ${SLACK_NOTIFICATION_CHANNEL}
      PORT: ${DB_PORT}
      GOOGLE_CALENDAR_API_KEY: ${GOOGLE_CALENDAR_API_KEY}
      GOOGLE_CALENDAR_ID: ${GOOGLE_CALENDAR_ID}
      SANITY_PROJECT_ID: ${SANITY_PROJECT_ID}
      SANITY_DATA_SET: ${SANITY_DATA_SET}
      AXIOM_API_TOKEN: ${AXIOM_API_TOKEN}

  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 8080:8080
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nemo
    volumes:
      - nemo_volume:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_db_admin
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: ${MONGO_CONNECTION_URI}

volumes:
  nemo_volume: ~
